GET http://localhost:9001
###
POST http://localhost:9001/login
Content-Type: application/json

{
    "email":"kaveen@gmail.com",
    "password":"kaveen"
}
###
GET http://localhost:9000/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imthc3VuaUBnbWFpbC5jb20iLCJpYXQiOjE2MTIwOTI0OTEsImV4cCI6MTYxMjA5NjA5MX0.IK_Zk5g-iuVmMNmj40F9S76yar29WXZODthkjaebeNg

{
    "device_id":"d0006"
    
}
###
POST http://localhost:9001/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imthc3VuaUBnbWFpbC5jb20iLCJpYXQiOjE2MTIwMjkwMjEsImV4cCI6MTYxMjAyOTA0MX0.dMU7-ukUjq88OOiFr9vqxTmDzKspDt9-C-Hn6q6F7g0"
}
###
DELETE http://localhost:9001/logout
Content-Type: application/json

{ 
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthdmVlbkBnbWFpbC5jb20iLCJpYXQiOjE2MTIxNjc5NDh9.Fg5uQMKi55wMP0QVM-ACqnrM6bfbl6rNeOwlPMzxfRE"
}
###
GET http://localhost:9000


